queue_rules:
  - name: default
    conditions:
      - status-success=lint (windows-latest)
      - status-success=lint (ubuntu-latest)
      - status-success=versio-plan
      - status-success=cargo-test (ubuntu-latest)
      - status-success=cargo-test (macos-latest)
      - status-success=cargo-test (windows-latest)
      - status-success=cargo-audit
      - status-success=cargo-check

pull_request_rules:
  - name: automatic rebase for dependencies
    conditions:
      - status-success=lint (windows-latest)
      - status-success=lint (ubuntu-latest)
      - status-success=versio-plan
      - status-success=cargo-test (ubuntu-latest)
      - status-success=cargo-test (macos-latest)
      - status-success=cargo-test (windows-latest)
      - status-success=cargo-audit
      - status-success=cargo-check
      - base=master
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      queue:
        method: rebase
        rebase_fallback: merge
        name: default
