ptions:
    prev_tag: versio-prev

projects:
    - name: specdown
      id: 1
      tag_prefix: ''
      labels: cargo
      version:
          file: Cargo.toml
          toml: package.version
      also:
          - file: docs/cli/display_help.md
            pattern: specdown (\d+\.\d+\.\d+)
          - file: docs/cli/display_help_windows.md
            pattern: specdown (\d+\.\d+\.\d+)
          - file: tests/command_test.rs
            pattern: specdown (\d+\.\d+\.\d+)
      hooks:
          post_write: cargo fetch

sizes:
    use_angular: true
    none: [ci, "-"]
